// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp86VVPxvdgJ3JH8mT5vxpp4882DqO9jk',
    appId: '1:12018282168:web:15b879eac5ae7091510e4d',
    messagingSenderId: '12018282168',
    projectId: 'quiz-maker-app-c6065',
    authDomain: 'quiz-maker-app-c6065.firebaseapp.com',
    storageBucket: 'quiz-maker-app-c6065.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDzkTnioZjwkrLNzUredh-iYentolB8dTE',
    appId: '1:12018282168:android:6d1f0bc560b08a1b510e4d',
    messagingSenderId: '12018282168',
    projectId: 'quiz-maker-app-c6065',
    storageBucket: 'quiz-maker-app-c6065.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp86VVPxvdgJ3JH8mT5vxpp4882DqO9jk',
    appId: '1:12018282168:web:7d5ddec1faac657c510e4d',
    messagingSenderId: '12018282168',
    projectId: 'quiz-maker-app-c6065',
    authDomain: 'quiz-maker-app-c6065.firebaseapp.com',
    storageBucket: 'quiz-maker-app-c6065.firebasestorage.app',
  );
}
